# Generated by Django 4.1.3 on 2022-12-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0002_showroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('paymentMethod', models.CharField(max_length=122)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
                ('date', models.DateField()),
            ],
        ),
    ]
