# Generated by Django 4.1.3 on 2022-12-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showroom', '0003_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showroom',
            name='price',
            field=models.CharField(max_length=100),
        ),
    ]
